### ISSUE TITLE
Can not download dataset ! i can't open the link, is there any other way to download?

### ISSUE THREAD

**Issue by xiaoyongbest1234** [tuyunbin/Video-Description-with-Spatial-Temporal-Attention#1]
i can't open the link, is there any other way to download?

**Comment by tuyunbin** [comment]
which link?

**Comment by xiaoyongbest1234** [comment]
In the Github project "video-description-with-spatial-temporal Attention" released by you, the following linked data cannot be downloaded smoothly:
    （1）The pre-processed datasets used in our paper are available at this links
    （2）global and motion features
    （3）local features
     After several attempts, I found that the MultCloud download could not obtain resources and could not download smoothly.I think maybe an alternative way of uploading data would be more efficient in providing downloads.
     I hope you can adjust the way of downloading at your convenience.Thank you very much.

**Comment by tuyunbin** [comment]
你好，下载链接我已经更新，有三个是谷歌云盘，有一个是百度云盘的。祝好！




------------------ 原始邮件 ------------------
发件人: "xiaoyongbest1234"<notifications@github.com>; 
发送时间: 2019年9月27日(星期五) 下午4:04
收件人: "tuyunbin/Video-Description-with-Spatial-Temporal-Attention"<Video-Description-with-Spatial-Temporal-Attention@noreply.github.com>; 
抄送: "Yunbin Tu"<1515503470@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [tuyunbin/Video-Description-with-Spatial-Temporal-Attention] Cannot download dataset ! i can't open the link, is there any other way todownload? (#1)



尊敬的涂云斌学长： 
      您好，我是来自中国民航大学计算机学院研二学生，目前正在研究“视觉描述”这个领域。在您发布的Github项目“Video-Description-with-Spatial-Temporal-Attention”中，有以下链接的数据无法顺利下载： 
     （1）The pre-processed datasets used in our paper are available at this links 
     （2）global and motion features 
     （3）local features 
      我通过多次尝试，发现MultCloud下载无法获取资源，不能顺利下载。学长，我觉得或许换种数据上传方式，能更有效地提供下载。 
      多有打扰，希望学长能在方便的时候，调整下载的方式。非常感谢。 
 
 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "涂云斌"<notifications@github.com>;  
 发送时间: 2019年9月27日(星期五) 中午11:48 
 收件人: "tuyunbin/Video-Description-with-Spatial-Temporal-Attention"<Video-Description-with-Spatial-Temporal-Attention@noreply.github.com>;  
 抄送: "*^&#717;^* 鎐篮曲"<847396171@qq.com>; "Author"<author@noreply.github.com>;  
 主题: Re: [tuyunbin/Video-Description-with-Spatial-Temporal-Attention] Cannot download dataset ! i can't open the link, is there any other way todownload? (#1) 
 
 
 
 
 which link?

**Comment by tuyunbin** [comment]
The above links have been updated.
