### ISSUE TITLE
The download link of local features needs a password, which can be provided？

### ISSUE THREAD

**Issue by HaiRanHaiRan** [tuyunbin/Video-Description-with-Spatial-Temporal-Attention#10]
This link https://pan.baidu.com/s/1TvZL0ktP2tMxNJV4kYCLeg
thanks

**Comment by tuyunbin** [comment]
Can you give me a screenshot? I click this link and don't need any password.

**Comment by HaiRanHaiRan** [comment]
![image](https://user-images.githubusercontent.com/39664317/82554076-cffc3200-9b97-11ea-8bd7-400da6903c09.png)
Maybe you typed it before

**Comment by tuyunbin** [comment]
> ![image](https://user-images.githubusercontent.com/39664317/82554076-cffc3200-9b97-11ea-8bd7-400da6903c09.png)
> Maybe you typed it before

The link is updated and extracting code is provided.
