### ISSUE TITLE
Last program gave error

### ISSUE THREAD

**Issue by 170987karan** [tuyunbin/Video-Description-with-Spatial-Temporal-Attention#16]
this error came when i run train_model.py
Please resolve this.
I am trying many times
plessss

args must be like a=X b.c=X
('current save dir ', './exp/test_non/')
./exp/test_non/ already exists!
preparing reload
('save dir ', './exp/test_non/')
('from_dir ', 'C:/Users/KARAN AGGARWAL/Downloads/workplace2/Video-Description-with-Spatial-Temporal-Attention-master/pre-trained_model/pre-trained_model/')
setting current model config with the old one
('erasing everything in ', './exp/test_non/')
saving model config into ./exp/test_non/model_config.pkl
Model Type: attention
Host:    karan
Command: C:\Users\KARAN AGGARWAL\Anaconda3\lib\site-packages\ipykernel_launcher.py -f C:\Users\KARAN AGGARWAL\AppData\Roaming\jupyter\runtime\kernel-c84b856d-7eba-49a8-af4f-6bbb14f0c953.json
training an attention model
Loading data
loading youtube2text googlenet features
C:\Users\KARAN AGGARWAL\Downloads\workplace2\Video-Description-with-Spatial-Temporal-Attention-master\model_attention.py:37: UserWarning: Feeding context to output directly seems to hurt.
  warnings.warn('Feeding context to output directly seems to hurt.')
uneven minibath chunking, overall 32, last one 12
uneven minibath chunking, overall 200, last one 91
uneven minibath chunking, overall 200, last one 168
init params
no lstm on ctx
Reloading model params...
buliding sampler
Building f_init... Done
building f_next...
Done
building f_log_probs
building f_alphal
building f_alphag
building f_alpham
building f_alphalt
compute grad
build train fns
compilation took 250.9914 sec
Optimization
loading history error...
Epoch  0
C:\Users\KARAN AGGARWAL\Anaconda3\lib\site-packages\theano\tensor\subtensor.py:2197: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  rval = inputs[0].__getitem__(inputs[1:])

**Comment by 170987karan** [comment]
this error came when i run train_model.py

**Comment by 170987karan** [comment]
Please resolve this.
I am trying many times
plessss

**Comment by tuyunbin** [comment]
Hi, since I have run this code on linux system, I don't konw whether it is compatible with window system. I strongly suggested you  run it on linux system in that I can help you to debug the error.
