### ISSUE TITLE
I cannot download the data of these two links('pre-trained_model' and 'local features').

### ISSUE THREAD

**Issue by Martin-top** [tuyunbin/Video-Description-with-Spatial-Temporal-Attention#3]
1. ["Firstly, you need to download the pre-trained model at this link" ](https://www.multcloud.com/share/e31c7520-c44c-450e-93c6-f367a235575b) This MultCloud cloud disk link is also undownloadable.Can you change it?

2. Also, can you provide the 'extraction code' for "local features"?

**Comment by tuyunbin** [comment]
1. I have changed the download link.
2. The extraction code of 'local features' is yv4q.
