### ISSUE TITLE
Can you change the links of three Google cloud to Baidu cloud？

### ISSUE THREAD

**Issue by aishenghuoaihh** [tuyunbin/Video-Description-with-Spatial-Temporal-Attention#6]
Because there is no way to get the vpn and turn over the wall, so can you please change the link to Baidu cloud? Thank you very much!

**Comment by tuyunbin** [comment]
I have additionally added the link of Baidu cloud in Readme.

**Comment by aishenghuoaihh** [comment]
Thank you very much for your quick reply！
