### ISSUE TITLE
what specific implementation steps can see the experimental results in the paper?

### ISSUE THREAD

**Issue by yanwencai001** [tuyunbin/Video-Description-with-Spatial-Temporal-Attention#8]
Hello, if I use the model you have trained, what specific execution steps can see the experimental results in the paper, and what files need to be run.

**Comment by yanwencai001** [comment]
Looking forward to your reply

**Comment by tuyunbin** [comment]
I'm sorry to reply you late. If you want to use my pre-trained model, you should change some settings in config.py. First, you should set 'True' in this line  https://github.com/tuyunbin/Video-Description-with-Spatial-Temporal-Attention/blob/962aa3c4fcc4401b48a4c9163fee302caa62acac/config.py#L12. Then, you should set the path of pre-trained model in this line   https://github.com/tuyunbin/Video-Description-with-Spatial-Temporal-Attention/blob/962aa3c4fcc4401b48a4c9163fee302caa62acac/config.py#L14.
Please note, I later added a embdding layer for local and motion features before they are fed into decoder, so the final scores are actually better than the scores in our paper.
